### ISSUE TITLE
Infografia  el ciclo de vida de un sistema

### ISSUE THREAD

**Issue by luzm23** [SistemasTecTlaxiaco/actividad-1-infografia-luzm23#2]
[Infografia ciclo de vida de un sistema .pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-luzm23/files/12489816/Infografia.ciclo.de.vida.de.un.sistema.pdf)

**Comment by YaelStO** [comment]
Excelente Trabajo 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
